CREATE TABLE MEMBER (
	MEM_NO	NUMBER	NULL,
	MEM_ID	VARCHAR2(100)	NULL,
	MEM_PW	VARCHAR2(30)	NULL,
	MEM_NICK	VARCHAR2(50)	NULL,
	ENROLL_DATE	DATE	NULL,
	SECESSION	CHAR(1)	NULL,
	MEM_EMAIL	VARCHAR2(200)	NULL,
	PHONE	VARCHAR2(100)	NULL,
	PROFILE_IMG	VARCHAR2(2000)	NULL
);

CREATE TABLE CONTEST (
	CONTEST_NO	NUMBER	NULL,
	CONTEST_NAME	VARCHAR(100)	NULL,
	CONTEST_FEE	VARCHAR(400)	NULL,
	CONTEST_DATE	VARCHAR(200)	NULL
);

CREATE TABLE CONTEST_MEMBER (
	MEM_NO	NUMBER	NULL,
	CONTEST_NO	NUMBER	NULL
);

CREATE TABLE BOARD (
	BOARD_NO	NUMBER	NULL,
	MEM_NO	NUMBER	NULL,
	BOARD_TITLE	VARCHAR2(300)	NULL,
	BOARD_CONTENTS	VARCHAR2(4000)	NULL,
	BOARD_IMG	VARCHAR2(3000)	NULL,
	BOARD_DATE	DATE	NULL,
	BOARD_ST	CHAR(1)	NULL
);

CREATE TABLE ANNOUNCE (
	ANN_NO	NUMBER	NULL,
	ANN_TITLE	VARCHAR2(300)	NULL,
	ANN_CONTENTS	VARCHAR2(4000)	NULL,
	ANN_IMG	VARCHAR2(3000)	NULL
);

CREATE TABLE RANKING (
	MEM_NO	NUMBER	NULL,
	WIN	NUMBER	NULL,
	DEFEAT	NUMBER	NULL
);

CREATE TABLE REPLY (
	REPLY_NO	NUMBER	NOT NULL,
	BOARD_NO	NUMBER	NULL,
	MEM_NO	NUMBER	NULL,
	REPLY_CONTENTS	VARCHAR2(300)	NULL,
	REPLY_DATE	DATE	NULL,
	REPLY_ST	CHAR(1)	NULL
);

CREATE TABLE CERTIFICATION (
	EMAIL	VARCHAR2(200)	NULL,
	C_NUMBER	NUMBER	NULL,
	ISSUE_DT	DATE	NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEM_NO
);

ALTER TABLE CONTEST ADD CONSTRAINT PK_CONTEST PRIMARY KEY (
	CONTEST_NO
);

ALTER TABLE CONTEST_MEMBER ADD CONSTRAINT PK_CONTEST_MEMBER PRIMARY KEY (
	MEM_NO,
	CONTEST_NO
);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	BOARD_NO,
	MEM_NO
);

ALTER TABLE ANNOUNCE ADD CONSTRAINT PK_ANNOUNCE PRIMARY KEY (
	ANN_NO
);

ALTER TABLE RANKING ADD CONSTRAINT PK_RANKING PRIMARY KEY (
	MEM_NO
);

ALTER TABLE REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY (
	REPLY_NO,
	BOARD_NO,
	MEM_NO
);

ALTER TABLE CONTEST_MEMBER ADD CONSTRAINT FK_MEMBER_TO_CONTEST_MEMBER_1 FOREIGN KEY (
	MEM_NO
)
REFERENCES MEMBER (
	MEM_NO
);

ALTER TABLE CONTEST_MEMBER ADD CONSTRAINT FK_CONTEST_TO_CONTEST_MEMBER_1 FOREIGN KEY (
	CONTEST_NO
)
REFERENCES CONTEST (
	CONTEST_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_MEMBER_TO_BOARD_1 FOREIGN KEY (
	MEM_NO
)
REFERENCES MEMBER (
	MEM_NO
);

ALTER TABLE RANKING ADD CONSTRAINT FK_MEMBER_TO_RANKING_1 FOREIGN KEY (
	MEM_NO
)
REFERENCES MEMBER (
	MEM_NO
);

ALTER TABLE REPLY ADD CONSTRAINT FK_BOARD_TO_REPLY_1 FOREIGN KEY (
	BOARD_NO
)
REFERENCES BOARD (
	BOARD_NO
);

ALTER TABLE REPLY ADD CONSTRAINT FK_MEMBER_TO_REPLY_1 FOREIGN KEY (
	MEM_NO
)
REFERENCES MEMBER (
	MEM_NO
);

